services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge 